import type { ModelDefinitionConfig } from "openclaw/plugin-sdk/provider-model-shared";

export const MODELVERSE_BASE_URL = "https://api.modelverse.cn/v1";


const DEFAULT_COST = {
  input: 0,
  output: 0,
  cacheRead: 0,
  cacheWrite: 0,
};

export const MODELVERSE_MODEL_CATALOG: ModelDefinitionConfig[] = [
  // ── OpenAI / GPT ─────────────────────────────────────────────────────────────
  // gpt-5.x chat models: openai-completions + image input
  // codex models: openai-responses only (no image)
  { id: "gpt-5.4",               name: "GPT-5.4",               api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.4-pro",           name: "GPT-5.4 Pro",           api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.4-mini",          name: "GPT-5.4 Mini",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.4-nano",          name: "GPT-5.4 Nano",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.3-chat-latest",   name: "GPT-5.3 Chat (latest)", api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.3-codex",         name: "GPT-5.3 Codex",         api: "openai-responses",   reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.2",               name: "GPT-5.2",               api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.2-chat",          name: "GPT-5.2 Chat",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.2-codex",         name: "GPT-5.2 Codex",         api: "openai-responses",   reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.1",               name: "GPT-5.1",               api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.1-chat",          name: "GPT-5.1 Chat",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.1-codex",         name: "GPT-5.1 Codex",         api: "openai-responses",   reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.1-codex-max",     name: "GPT-5.1 Codex Max",     api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5.1-codex-mini",    name: "GPT-5.1 Codex Mini",    api: "openai-responses",   reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5",                 name: "GPT-5",                 api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5-chat",            name: "GPT-5 Chat",            api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-5-codex",           name: "GPT-5 Codex",           api: "openai-responses",   reasoning: false, input: ["text"],          contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5.2",        name: "GPT-5.2 (openai/)",     api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5.1",        name: "GPT-5.1 (openai/)",     api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5.1-chat",   name: "GPT-5.1 Chat (openai/)", api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5.1-codex",  name: "GPT-5.1 Codex (openai/)", api: "openai-responses", reasoning: false, input: ["text"],          contextWindow: 200000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5.1-codex-mini", name: "GPT-5.1 Codex Mini (openai/)", api: "openai-responses", reasoning: false, input: ["text"], contextWindow: 200000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5",          name: "GPT-5 (openai/)",       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5-mini",     name: "GPT-5 Mini (openai/)",  api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-5-nano",     name: "GPT-5 Nano (openai/)",  api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000,  maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-4.1",        name: "GPT-4.1 (openai/)",     api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "openai/gpt-4o",         name: "GPT-4o (openai/)",      api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 128000,  maxTokens: 16384,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-4.1-mini",          name: "GPT-4.1 Mini",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-4.1-nano",          name: "GPT-4.1 Nano",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-4o-240806",         name: "GPT-4o (2024-08-06)",   api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 128000,  maxTokens: 16384,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-4o-mini",           name: "GPT-4o Mini",           api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 128000,  maxTokens: 16384,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gpt-oss-120b",          name: "GPT OSS 120B",          api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 128000,  maxTokens: 16384,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── OpenAI reasoning ────────────────────────────────────────────────────────
  { id: "o4-mini",            name: "o4-mini",         api: "openai-completions", reasoning: true, input: ["text", "image"], contextWindow: 200000, maxTokens: 100000, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "o3-2025-04-16",      name: "o3 (2025-04-16)", api: "openai-completions", reasoning: true, input: ["text", "image"], contextWindow: 200000, maxTokens: 100000, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "o3-mini",            name: "o3-mini",         api: "openai-completions", reasoning: true, input: ["text"],          contextWindow: 200000, maxTokens: 65536,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "o1",                 name: "o1",              api: "openai-completions", reasoning: true, input: ["text", "image"], contextWindow: 200000, maxTokens: 100000, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // codex-mini-latest uses the OpenAI Codex responses API
  { id: "codex-mini-latest",  name: "Codex Mini (latest)", api: "openai-codex-responses", reasoning: false, input: ["text"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Anthropic Claude ─────────────────────────────────────────────────────────
  // All Claude models support openai-completions and image input
  { id: "claude-opus-4-6",                     name: "Claude Opus 4.6",                         api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4-6",                   name: "Claude Sonnet 4.6",                       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-4-opus",                       name: "Claude 4 Opus",                           api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-4-sonnet",                     name: "Claude 4 Sonnet",                         api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4-5-20251101",            name: "Claude Opus 4.5 (2025-11-01)",            api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4-5-20251101-thinking",   name: "Claude Opus 4.5 Thinking (2025-11-01)",  api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4-1-20250805",            name: "Claude Opus 4.1 (2025-08-05)",            api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4-1",                     name: "Claude Opus 4.1",                         api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4.1-thinking",            name: "Claude Opus 4.1 Thinking",                api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-opus-4.0-thinking",            name: "Claude Opus 4.0 Thinking",                api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4.0-thinking",          name: "Claude Sonnet 4.0 Thinking",              api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4.5",                   name: "Claude Sonnet 4.5",                       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4.5-thinking",          name: "Claude Sonnet 4.5 Thinking",              api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4-5-20250929",          name: "Claude Sonnet 4.5 (2025-09-29)",          api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-4-5-20250929-thinking", name: "Claude Sonnet 4.5 Thinking (2025-09-29)", api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 200000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-3.7",                   name: "Claude Sonnet 3.7",                       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-sonnet-3.5",                   name: "Claude Sonnet 3.5",                       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "claude-haiku-4-5-20251001",           name: "Claude Haiku 4.5 (2025-10-01)",           api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 200000, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── DeepSeek ─────────────────────────────────────────────────────────────────
  { id: "deepseek-ai/DeepSeek-V3.2",                  name: "DeepSeek V3.2",              api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.2-Exp",              name: "DeepSeek V3.2 Exp",          api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.2-Think",            name: "DeepSeek V3.2 Think",        api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.2-Exp-Think",        name: "DeepSeek V3.2 Exp Think",    api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.1",                  name: "DeepSeek V3.1",              api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.1-0821",             name: "DeepSeek V3.1 (08-21)",      api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.1-Terminus",         name: "DeepSeek V3.1 Terminus",     api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3.1-Think",            name: "DeepSeek V3.1 Think",        api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-V3-0324",               name: "DeepSeek V3 (03-24)",        api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-R1",                    name: "DeepSeek R1",                api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-R1-0528",               name: "DeepSeek R1 (05-28)",        api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",  name: "DeepSeek R1 Distill Llama 70B", api: "openai-completions", reasoning: true, input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Qwen / Alibaba ───────────────────────────────────────────────────────────
  // VL (vision-language) models accept image input; standard models are text-only
  { id: "Qwen/Qwen3-Max",                        name: "Qwen3 Max",                    api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-max-2025-09-23",                  name: "Qwen3 Max (2025-09-23)",       api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-max-preview",                     name: "Qwen3 Max Preview",            api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-235B-A22B-Thinking-2507",   name: "Qwen3 235B Thinking",          api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-235b-a22b-instruct-2507",         name: "Qwen3 235B Instruct",          api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-32B",                        name: "Qwen3 32B",                    api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-32B-Thinking",               name: "Qwen3 32B Thinking",           api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-30B-A3B-Thinking",           name: "Qwen3 30B-A3B Thinking",       api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-30b-a3b",                         name: "Qwen3 30B-A3B",                api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-30b-a3b-instruct-2507",           name: "Qwen3 30B-A3B Instruct",       api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-Coder",                      name: "Qwen3 Coder",                  api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-coder-plus",                      name: "Qwen3 Coder Plus",             api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-coder-30b-a3b-instruct",          name: "Qwen3 Coder 30B-A3B Instruct", api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-VL-235B-A22B-Instruct",     name: "Qwen3 VL 235B Instruct",       api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-VL-235B-A22B-Thinking",     name: "Qwen3 VL 235B Thinking",       api: "openai-completions", reasoning: true,  input: ["text", "image"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen3-vl-Plus",                   name: "Qwen3 VL Plus",                api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3-vl-flash",                        name: "Qwen3 VL Flash",               api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen-Plus",                        name: "Qwen Plus",                    api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/Qwen-Plus-Thinking",               name: "Qwen Plus Thinking",           api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "Qwen/QwQ-32B",                          name: "QwQ-32B",                      api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3.6-plus",                          name: "Qwen3.6 Plus",                 api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen3.5-plus",                          name: "Qwen3.5 Plus",                 api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "qwen-turbo",                            name: "Qwen Turbo",                   api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Doubao / ByteDance ───────────────────────────────────────────────────────
  { id: "doubao-seed-2-0-pro-260215",          name: "Doubao Seed 2.0 Pro",             api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "doubao-seed-2-0-code-preview-260215", name: "Doubao Seed 2.0 Code Preview",   api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "doubao-seed-2-0-lite-260215",         name: "Doubao Seed 2.0 Lite",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "doubao-seed-2-0-mini-260215",         name: "Doubao Seed 2.0 Mini",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "doubao-seed-1-6-lite-251015",         name: "Doubao Seed 1.6 Lite",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "doubao-1-5-pro-32k-character-250715", name: "Doubao 1.5 Pro 32K Character",   api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 32768,  maxTokens: 4096,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "ByteDance/doubao-seed-1.6",           name: "Doubao Seed 1.6 (ByteDance/)",   api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "ByteDance/doubao-1-5-pro-32k-250115", name: "Doubao 1.5 Pro 32K (ByteDance/)", api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 32768, maxTokens: 4096,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Grok / xAI ───────────────────────────────────────────────────────────────
  { id: "grok-4",                      name: "Grok 4",              api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "grok-4-fast",                 name: "Grok 4 Fast",         api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "grok-4-fast-reasoning",       name: "Grok 4 Fast Reasoning", api: "openai-completions", reasoning: true, input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "grok-4-1-fast-reasoning",     name: "Grok 4.1 Fast Reasoning", api: "openai-completions", reasoning: true, input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "grok-4-1-fast-non-reasoning", name: "Grok 4.1 Fast",       api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Moonshot / Kimi ──────────────────────────────────────────────────────────
  { id: "moonshotai/kimi-k2.5",             name: "Kimi K2.5 (moonshotai/)",   api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "moonshot/kimi-k2.5",               name: "Kimi K2.5 (moonshot/)",     api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "moonshotai/Kimi-K2-Instruct",      name: "Kimi K2 Instruct",          api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "moonshotai/Kimi-K2-Instruct-0905", name: "Kimi K2 Instruct (09-05)",  api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "moonshotai/Kimi-K2-Thinking",      name: "Kimi K2 Thinking",          api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── MiniMax ──────────────────────────────────────────────────────────────────
  { id: "MiniMax-M2.7",           name: "MiniMax M2.7",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2.7-highspeed", name: "MiniMax M2.7 Highspeed", api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2.5",           name: "MiniMax M2.5",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2.5-lightning", name: "MiniMax M2.5 Lightning", api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2.1",           name: "MiniMax M2.1",           api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2.1-lightning", name: "MiniMax M2.1 Lightning", api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiniMax-M2",             name: "MiniMax M2",             api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── GLM / Zhipu AI ───────────────────────────────────────────────────────────
  // GLM-xV (vision) models accept image input
  { id: "zai-org/glm-5",    name: "GLM-5 (zai-org/)",    api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "glm-5.1",          name: "GLM-5.1",              api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "glm-5-turbo",      name: "GLM-5 Turbo",          api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "glm-5v-turbo",     name: "GLM-5V Turbo",         api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "zai-org/glm-4.7",  name: "GLM-4.7 (zai-org/)",  api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "zai-org/glm-4.6",  name: "GLM-4.6 (zai-org/)",  api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "zai-org/glm-4.6v", name: "GLM-4.6V (zai-org/)", api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "zai-org/glm-4.5",  name: "GLM-4.5 (zai-org/)",  api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "zai-org/glm-4.5v", name: "GLM-4.5V (zai-org/)", api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Baidu ERNIE ──────────────────────────────────────────────────────────────
  { id: "baidu/ernie-4.5-turbo-128k",   name: "ERNIE 4.5 Turbo 128K",    api: "openai-completions", reasoning: false, input: ["text"],          contextWindow: 131072, maxTokens: 8192, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "baidu/ernie-4.5-turbo-vl-32k", name: "ERNIE 4.5 Turbo VL 32K", api: "openai-completions", reasoning: false, input: ["text", "image"], contextWindow: 32768,  maxTokens: 8192, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "baidu/ernie-x1-turbo-32k",     name: "ERNIE X1 Turbo 32K",      api: "openai-completions", reasoning: true,  input: ["text"],          contextWindow: 32768,  maxTokens: 8192, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  // ── Others ───────────────────────────────────────────────────────────────────
  { id: "google/gemma-3-27b-it", name: "Gemma 3 27B IT",  api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "kat-coder-256k",        name: "Kat Coder 256K",  api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 262144, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "mimo-v2-pro",           name: "Mimo V2 Pro",     api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 16384, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "mimo-v2-flash",         name: "Mimo V2 Flash",   api: "openai-completions", reasoning: false, input: ["text"], contextWindow: 131072, maxTokens: 8192,  cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "MiroThinker-1.7",       name: "MiroThinker 1.7", api: "openai-completions", reasoning: true,  input: ["text"], contextWindow: 131072, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
];

// Default api is openai-completions; per-model api field overrides this.
export function buildModelverseModelDefinition(
  model: (typeof MODELVERSE_MODEL_CATALOG)[number],
): ModelDefinitionConfig {
  return {
    api: "openai-completions",
    ...model,
  };
}

// TODO: Gemini models require a separate base URL (https://api.modelverse.cn/v1beta) and the google-generative-ai protocol.
// Not included in the main catalog until
export const MODELVERSE_GEMINI_BASE_URL = "https://api.modelverse.cn/v1beta";
export const MODELVERSE_GEMINI_CATALOG: ModelDefinitionConfig[] = [
  { id: "gemini-3.1-pro-preview",                           name: "Gemini 3.1 Pro Preview",               api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gemini-3.1-flash-lite-preview",                    name: "Gemini 3.1 Flash Lite Preview",        api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gemini-3-flash-preview",                           name: "Gemini 3 Flash Preview",               api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "publishers/google/models/gemini-3.1-pro-preview",  name: "Gemini 3.1 Pro Preview (publishers/)", api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "publishers/google/models/gemini-3-flash-preview",  name: "Gemini 3 Flash Preview (publishers/)", api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gemini-2.5-pro",                                   name: "Gemini 2.5 Pro",                       api: "google-generative-ai", reasoning: true,  input: ["text", "image"], contextWindow: 1000000, maxTokens: 65536, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
  { id: "gemini-2.5-flash",                                 name: "Gemini 2.5 Flash",                     api: "google-generative-ai", reasoning: false, input: ["text", "image"], contextWindow: 1000000, maxTokens: 32768, cost: DEFAULT_COST, compat: { supportsUsageInStreaming: true } },
];
